$(function(){
    $(".nav>ul>li").mouseover(function(){
        $('.submenu').stop().slideDown(300)
        $('#header').addClass("on")
    })
    $(".nav>ul>li").mouseout(function(){
        $('.submenu').stop().slideUp(100)
        $('#header').removeClass("on")
    })
})